# Generated by Django 3.2 on 2022-11-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpost',
            name='title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
