# Generated by Django 3.2 on 2022-11-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostsApp', '0002_allpost_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPostFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostId', models.IntegerField()),
                ('Author', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('cover', models.FileField(upload_to='')),
            ],
        ),
    ]
