# Generated by Django 3.2.10 on 2022-11-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0004_modules_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('room', models.IntegerField()),
                ('guest', models.CharField(max_length=50)),
            ],
        ),
    ]
