# Generated by Django 3.2.10 on 2022-11-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0005_myreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyHotelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('hotel_id', models.IntegerField()),
                ('roomquantity', models.IntegerField()),
                ('remaining', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='myreservation',
            name='hotel_id',
            field=models.IntegerField(default=0),
        ),
    ]
