# Generated by Django 3.2.10 on 2022-11-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0006_auto_20221119_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='myreservation',
            name='roomquantity',
            field=models.IntegerField(default=0),
        ),
    ]
