# Generated by Django 3.2.10 on 2022-11-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0007_myreservation_roomquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='myreservation',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
