# Generated by Django 3.2.10 on 2022-11-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0009_myreservation_cardata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTourInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_id', models.IntegerField()),
                ('month', models.CharField(max_length=50)),
                ('tourquantity', models.IntegerField(default=0)),
            ],
        ),
    ]
