# Generated by Django 3.2.10 on 2022-11-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0010_mytourinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytourinfo',
            name='month',
            field=models.IntegerField(),
        ),
    ]
